# Generated by Django 2.2 on 2020-05-03 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='taxon',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='id_of_plant',
        ),
        migrations.AddField(
            model_name='plant',
            name='barcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='collector',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='plant',
            name='legend_author',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='plant',
            name='locality',
            field=models.CharField(default='Bratislava', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='country',
            field=models.CharField(choices=[('Slovensko', 'Slovakia'), ('Cesko', 'Czechia'), ('Rakusko', 'Austria'), ('Polsko', 'Poland')], default=('Slovensko', 'Slovakia'), max_length=30),
        ),
    ]
